
site_name: TriCal
site_description: Trapped-ion Calculator

repo_name: OpenQuantumDesign/TrICal
repo_url: https://github.com/OpenQuantumDesign/TrICal

copyright: Copyright &copy; 2024 Open Quantum Design

nav:
  - Introduction: index.md


use_directory_urls: false

theme:
  name: material

  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: light-blue
    accent: orange
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: light-blue
    accent: orange
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode

  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select

plugins:
  - mkdocstrings


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.blocks.admonition
  - pymdownx.blocks.details

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
